export const realSliceBusinesses = [
  {
    id: "news-cafe",
    name: "News Cafe",
    category: "restaurant",
    coords: [-80.1314449, 25.7781319],
    address: "800 Ocean Drive, Miami Beach, FL, 33139",
    completeness: 65,
    source: "osm",
    sourceLicense: "ODbL 1.0",
    fields: { phone: true, website: true, hours: true },
    facts: [
      { key: "outdoor_seating", label: "Outdoor seating", prompt: "Can you confirm if this place still has outdoor seating facing Ocean Drive?", confirmations: 2, target: 3, options: ["Yes", "No", "Not sure"] },
      { key: "price_level", label: "Price level", prompt: "What price band feels right right now?", confirmations: 1, target: 3, options: ["$", "$$", "$$$", "$$$$"] },
      { key: "reservations", label: "Reservations", prompt: "Do they actively take reservations?", confirmations: 0, target: 3, options: ["Yes", "No", "Unsure"] },
    ],
  },
  {
    id: "giannis-at-the-villa",
    name: "Gianni’s At The Villa",
    category: "restaurant",
    coords: [-80.1305367, 25.7820009],
    address: "1116 Ocean Drive, Miami Beach, FL, 33139",
    completeness: 40,
    source: "osm",
    sourceLicense: "ODbL 1.0",
    fields: { phone: false, website: true, hours: false },
    facts: [
      { key: "phone", label: "Phone number", prompt: "Can a player confirm the public booking phone number?", confirmations: 0, target: 3, options: ["Add later", "Verified", "Unavailable"] },
      { key: "hours", label: "Opening hours", prompt: "Are the current service hours still correct?", confirmations: 0, target: 3, options: ["Confirm", "Changed", "Unsure"] },
      { key: "dress_code", label: "Dress code", prompt: "Is there an enforced dress code for dinner?", confirmations: 1, target: 3, options: ["Yes", "No", "Unsure"] },
    ],
  },
  {
    id: "havana-1957-ocean",
    name: "Havana 1957",
    category: "restaurant",
    coords: [-80.1300004, 25.7854963],
    address: "1410 Ocean Drive, Miami Beach, FL, 33139",
    completeness: 50,
    source: "osm",
    sourceLicense: "ODbL 1.0",
    fields: { phone: true, website: true, hours: false },
    facts: [
      { key: "hours", label: "Opening hours", prompt: "Can someone confirm lunch-to-late-night hours?", confirmations: 1, target: 3, options: ["Correct", "Need update", "Unsure"] },
      { key: "happy_hour", label: "Happy hour", prompt: "Does this branch currently run happy hour?", confirmations: 0, target: 3, options: ["Yes", "No", "Unsure"] },
      { key: "live_music", label: "Live music", prompt: "Is live music still part of the experience?", confirmations: 1, target: 3, options: ["Yes", "No", "Unsure"] },
    ],
  },
  {
    id: "pelican-cafe",
    name: "Pelican Café",
    category: "cafe",
    coords: [-80.131218, 25.778376],
    address: "826 Ocean Drive, Miami Beach, FL, 33139",
    completeness: 40,
    source: "osm",
    sourceLicense: "ODbL 1.0",
    fields: { phone: false, website: true, hours: false },
    facts: [
      { key: "phone", label: "Phone number", prompt: "Can the public phone number be verified?", confirmations: 0, target: 3, options: ["Verified", "Unavailable", "Unsure"] },
      { key: "hours", label: "Opening hours", prompt: "Does the breakfast service start early?", confirmations: 0, target: 3, options: ["Confirm", "Update needed", "Unsure"] },
      { key: "coffee_bar", label: "Coffee bar", prompt: "Is it still functioning more like a cafe than a full restaurant?", confirmations: 1, target: 3, options: ["Yes", "No", "Mixed"] },
    ],
  },
  {
    id: "11th-street-diner",
    name: "11th Street Diner",
    category: "restaurant",
    coords: [-80.1323342, 25.7818044],
    address: "1065 Washington Avenue, Miami Beach, FL, 33139",
    completeness: 65,
    source: "osm",
    sourceLicense: "ODbL 1.0",
    fields: { phone: true, website: true, hours: true },
    facts: [
      { key: "late_night", label: "Late-night service", prompt: "Is it still a reliable late-night stop?", confirmations: 2, target: 3, options: ["Yes", "No", "Unsure"] },
      { key: "breakfast_all_day", label: "Breakfast all day", prompt: "Can someone confirm breakfast service all day?", confirmations: 1, target: 3, options: ["Yes", "No", "Unsure"] },
      { key: "outdoor_seating", label: "Outdoor seating", prompt: "Is the sidewalk seating currently active?", confirmations: 0, target: 3, options: ["Yes", "No", "Unsure"] },
    ],
  },
  {
    id: "bolivar-restaurant-bar",
    name: "Bolivar Restaurant Bar",
    category: "restaurant",
    coords: [-80.1329751, 25.7790699],
    address: "841 Washington Avenue, Miami Beach, FL, 33139",
    completeness: 50,
    source: "osm",
    sourceLicense: "ODbL 1.0",
    fields: { phone: true, website: true, hours: false },
    facts: [
      { key: "hours", label: "Opening hours", prompt: "Can the restaurant + bar hours be confirmed?", confirmations: 1, target: 3, options: ["Correct", "Need update", "Unsure"] },
      { key: "live_music", label: "Live music", prompt: "Is live music still part of the offer?", confirmations: 0, target: 3, options: ["Yes", "No", "Unsure"] },
      { key: "outdoor_seating", label: "Outdoor seating", prompt: "Is the terrace currently in service?", confirmations: 1, target: 3, options: ["Yes", "No", "Unsure"] },
    ],
  },
  {
    id: "macchialina",
    name: "Macchialina",
    category: "restaurant",
    coords: [-80.1410217, 25.7786012],
    address: "820 Alton Road, Miami Beach, FL, 33139",
    completeness: 65,
    source: "osm",
    sourceLicense: "ODbL 1.0",
    fields: { phone: true, website: true, hours: true },
    facts: [
      { key: "reservations", label: "Reservations", prompt: "Do reservations remain strongly recommended?", confirmations: 2, target: 3, options: ["Yes", "No", "Unsure"] },
      { key: "price_level", label: "Price level", prompt: "Which price band feels accurate?", confirmations: 1, target: 3, options: ["$$", "$$$", "$$$$"] },
      { key: "outdoor_seating", label: "Outdoor seating", prompt: "Is patio seating available right now?", confirmations: 0, target: 3, options: ["Yes", "No", "Unsure"] },
    ],
  },
  {
    id: "crunch-fitness-washington",
    name: "Crunch Fitness",
    category: "gym",
    coords: [-80.1318353, 25.7838156],
    address: "1259 Washington Avenue, Miami Beach, FL, 33139",
    completeness: 55,
    source: "osm",
    sourceLicense: "ODbL 1.0",
    fields: { phone: true, website: false, hours: true },
    facts: [
      { key: "website", label: "Website", prompt: "Can someone link the correct location page?", confirmations: 0, target: 3, options: ["Verified", "Unavailable", "Unsure"] },
      { key: "day_pass", label: "Day pass", prompt: "Can visitors still buy a day pass?", confirmations: 1, target: 3, options: ["Yes", "No", "Unsure"] },
      { key: "locker_room", label: "Locker rooms", prompt: "Are locker rooms and showers accessible?", confirmations: 1, target: 3, options: ["Yes", "No", "Unsure"] },
    ],
  },
  {
    id: "yoga-lab",
    name: "Yoga Lab",
    category: "gym",
    coords: [-80.1328414, 25.7764027],
    address: "644 Collins Avenue, Miami Beach, FL, 33139",
    completeness: 30,
    source: "osm",
    sourceLicense: "ODbL 1.0",
    fields: { phone: false, website: false, hours: false },
    facts: [
      { key: "phone", label: "Phone number", prompt: "Can a player verify the public contact number?", confirmations: 0, target: 3, options: ["Verified", "Unavailable", "Unsure"] },
      { key: "website", label: "Website", prompt: "Is there an active booking website?", confirmations: 0, target: 3, options: ["Yes", "No", "Unsure"] },
      { key: "drop_in", label: "Drop-in classes", prompt: "Do they still allow drop-in sessions?", confirmations: 1, target: 3, options: ["Yes", "No", "Unsure"] },
    ],
  },
  {
    id: "south-beach-boxing",
    name: "South Beach Boxing",
    category: "gym",
    coords: [-80.1331672, 25.7774652],
    address: "723;715 Washington Avenue, Miami Beach, FL, 33139",
    completeness: 30,
    source: "osm",
    sourceLicense: "ODbL 1.0",
    fields: { phone: false, website: false, hours: false },
    facts: [
      { key: "phone", label: "Phone number", prompt: "Can the front desk phone be confirmed?", confirmations: 0, target: 3, options: ["Verified", "Unavailable", "Unsure"] },
      { key: "website", label: "Website", prompt: "Is there an active booking page or Instagram profile?", confirmations: 0, target: 3, options: ["Yes", "No", "Unsure"] },
      { key: "intro_session", label: "Intro session", prompt: "Do they still offer beginner sessions?", confirmations: 1, target: 3, options: ["Yes", "No", "Unsure"] },
    ],
  },
];
